''
'' qgl.bi -- the qgl layer's constants, for BASIC callers.
''
'' GENERATED by tools/mkqglbi.py from qgl.inc. Do not edit: the
'' build regenerates it and fails if this copy has drifted.
''
'' It exists because the same fact was kept in two places and did
'' drift -- SurfaceOps grew, the assembly's EMS became 10 and this
'' file still said 2, so a BASIC caller asking for an EMS surface
'' indexed the middle of the conventional-memory entry.
''

'' Which free figure qglMemAvail should report.
const QGL_MEM_LARGEST = 0
const QGL_MEM_TOTAL   = 2

'' Where a surface's pixels live.
const QGL_SURF_CMEM = 0
const QGL_SURF_EMS  = 2

'' Physical EMS page a surface is mapped through.
const QGL_TEX_SLOT = 0
const QGL_Z_SLOT   = 1

'' Depth mode, for qglSfZMode.
const QGL_Z_OFF  = 0
const QGL_Z_SET  = 1
const QGL_Z_TEST = 2

'' Drawing mode, for qglRsPoly.
const QGL_M_WIRE = 0
const QGL_M_FLAT = 1
const QGL_M_TEX  = 2
const QGL_M_PTEX = 3
const QGL_M_ATEX = 4

'' Where a paged array store's records live.
const QGL_AR_MEM = 0
const QGL_AR_EMS = 1

'' Pixel format, for qglNew/qglNewEx. One format, because the fill directory says so -- a second would be a sibling directory and a second table, never a flag.
const QGL_FMT_8BIT = 0
