/*
 * qgl.h -- the qgl layer, for C callers.
 *
 * GENERATED by tools/mkqglh.py from src/qgl. Do not edit: the
 * build regenerates it and fails if this copy has drifted.
 */
#ifndef QGL_H
#define QGL_H
#include "qgltypes.h"

/* Which free figure qglMemAvail should report. */
#define QGL_MEM_LARGEST 0
#define QGL_MEM_TOTAL   2

/* Where a surface's pixels live. */
#define QGL_SURF_CMEM 0
#define QGL_SURF_EMS  2

/* Physical EMS page a surface is mapped through. */
#define QGL_TEX_SLOT 0
#define QGL_Z_SLOT   1

/* Depth mode, for qglSfZMode. */
#define QGL_Z_OFF  0
#define QGL_Z_SET  1
#define QGL_Z_TEST 2

/* Drawing mode, for qglRsPoly. */
#define QGL_M_WIRE 0
#define QGL_M_FLAT 1
#define QGL_M_TEX  2
#define QGL_M_PTEX 3

/* Where a paged array store's records live. */
#define QGL_AR_MEM 0
#define QGL_AR_EMS 1

/* Pixel format, for qglNew/qglNewEx. One format, because the fill directory says so -- a second would be a sibling directory and a second table, never a flag. */
#define QGL_FMT_8BIT 0

/* far pascal, which is qgl.inc's own rule for every qgl_ entry. */

short pascal far qglAbi( short what );
void pascal far qglArFree( long h );
short pascal far qglArHandle( long h );
long pascal far qglArLoad( long path, short typ, short elsz, long cnt, short slot );
long pascal far qglArNew( short typ, short elsz, long cnt, short slot );
short pascal far qglArPages( long h );
short pascal far qglArPerpg( long h );
long pascal far qglArWin( long h, long idx );
void pascal far qglB8Selftest( void );
short pascal far qglClPoly( long src, short n, long dst, long sf );
short pascal far qglClPolyEx( long src, short n, long dst, long sf, short base, short step );
void pascal far qglClRect( short x0, short y0, short x1, short y1 );
void pascal far qglDelView( long sf );
void pascal far qglDrBlit( long d, short x, short y, long s );
void pascal far qglDrBlitScl( long d, short x, short y, short w, short h, long s );
void pascal far qglDrFill( long d, short x0, short y0, short x1, short y1, short col );
void pascal far qglDrHline( long d, short x0, short y, short x1, short col );
void pascal far qglDrLine( long d, short x0, short y0, short x1, short y1, short col );
void pascal far qglDrRect( long d, short x0, short y0, short x1, short y1, short col );
void pascal far qglDrShade( long d, short x0, short y0, short x1, short y1, long lut, short row );
void pascal far qglDrVline( long d, short x, short y0, short y1, short col );
long pascal far qglDspBuf( void );
short pascal far qglDspInit( short rate );
short pascal far qglDspPos( void );
long pascal far qglDspScratch( void );
short pascal far qglDspScratchBytes( void );
void pascal far qglDspShutdown( void );
void pascal far qglFileClose( short h );
short pascal far qglFileDrivers( void );
short pascal far qglFileNameBas( short s, long dst, short cap );
short pascal far qglFileOpen( const char far * path );
long pascal far qglFileRawRead( short fh, long dst, long nbytes );
short pascal far qglFileRawSeek( short fh, short whence, long pos );
long pascal far qglFileRawSize( short fh );
long pascal far qglFileRawWrite( short fh, long src, long nbytes );
long pascal far qglFileRead( short h, long dst, long nbytes );
long pascal far qglFileSize( short h );
long pascal far qglFileWrite( short h, long src, long nbytes );
short pascal far qglGemAlloc( long nbytes );
short pascal far qglGemFrame( void );
void pascal far qglGemFree( short hnd );
short pascal far qglGemInit( void );
short pascal far qglGemMap( short hnd, short logpage, short slot );
void pascal far qglGetClipRect( long sf, void far * cr );
void pascal far qglGetSetClipRect( long sf, void far * inCr, void far * outCr );
void pascal far qglKbdInit( Keys far * keys );
void pascal far qglKbdShutdown( void );
void pascal far qglM4Conc( Mat4 far * pOut, Mat4 far * pIna, Mat4 far * pInb );
void pascal far qglM4LookAt( Mat4 far * pOut, Vec3 far * pEye, Vec3 far * pAt, Vec3 far * pUp );
void pascal far qglM4Persp( Mat4 far * pOut, float fov, float asp, float zn, float zf );
long pascal far qglMemAlloc( long nbytes );
long pascal far qglMemAvail( short what );
void pascal far qglMemCopy( long dst, long src, long nbytes );
void pascal far qglMemFree( long p );
void pascal far qglMemInit( void );
void pascal far qglMemShutdown( void );
void pascal far qglMouseEvent( void );
short pascal far qglMouseInit( MouseInf far * m, short xmax, short ymax );
void pascal far qglMousePos( short x, short y );
void pascal far qglMouseShutdown( void );
long pascal far qglNew( short typ, short fmt, short xRes, short yRes );
long pascal far qglNewEx( short typ, short fmt, short xRes, short yRes, short bps, short pages );
long pascal far qglNewView( long src, long ofs, short xRes, short yRes );
long pascal far qglPrfTake( short k );
void pascal far qglRowRead( long sf, short x, short y, short pixels, short buffFmt, long buff );
void pascal far qglRowWrite( long sf, short x, short y, short pixels, short buffFmt, long buff );
void pascal far qglRowWriteEx( long sf, short x, short y, short pixels, short buffFmt, long buff, short opt );
void pascal far qglRsCover( short on );
void pascal far qglRsCoverClear( void );
short pascal far qglRsPoly( long d, void far * v, short n, short mode, long src );
void pascal far qglRsRef( short on );
short pascal far qglSbBuild( long dstDc, long texDc, long parm );
short pascal far qglSbReserve( void );
void pascal far qglSetClipRect( long sf, void far * cr );
short pascal far qglSetView( long sf, long ofs );
long pascal far qglSfAccessRd( long sf, short y );
long pascal far qglSfAccessRdEx( long sf, short y, short slot );
long pascal far qglSfAccessRdWr( long sf, short y, void * rdPtr );
long pascal far qglSfAccessWr( long sf, short y );
long pascal far qglSfAccessWrEx( long sf, short y, short slot );
void pascal far qglSfFree( long s );
long pascal far qglSfFromFileBas( short path, short wide, short kind );
void pascal far qglSfGet( long sf, long sfInfo );
short pascal far qglSfInit( void );
short pascal far qglSfLoad( long s, long path );
long pascal far qglSfNew( short wid, short hgt, short whr );
void pascal far qglSfNewEx( short wid, short hgt, short strd, short whr );
short pascal far qglSfPget( long s, short x, short y );
void pascal far qglSfPset( long s, short x, short y, short col );
long pascal far qglSfRdRow( long s, short y );
void pascal far qglSfRdRowEx( long s, short y, short slot );
long pascal far qglSfRow( long s, short y );
short pascal far qglSfSize( long s, short sel );
short pascal far qglSfViewAim( long v, long ofs );
long pascal far qglSfViewNew( long parent, short wid, short hgt, short bps );
short pascal far qglSfViewShape( long v, short wid, long ofs );
short pascal far qglSfWindows( long s );
long pascal far qglSfWrRow( long s, short y );
void pascal far qglSfWrRowEx( long s, short y, short slot );
void pascal far qglSfZClear( long surf, short val );
void pascal far qglSfZFree( long surf );
short pascal far qglSfZMode( long surf, short mode );
long pascal far qglSfZNew( long surf, short kind );
long pascal far qglTmrCycles( void );
long pascal far qglTmrHz( void );
void pascal far qglTmrInit( short hz );
void pascal far qglTmrShutdown( void );
long pascal far qglTmrTicks( void );
short pascal far qglTxtChar( long dst, short x, short y, long f, short glyph, short col );
void pascal far qglTxtFree( long f );
long pascal far qglTxtLoad( const char far * path );
short pascal far qglTxtRow( long f, short glyph, short row );
void pascal far qglTxtStr( long dst, short x, short y, long f, long s, short col );
short pascal far qglTxtWidth( long f, long s );
long pascal far qglVgaInit( void );
void pascal far qglVgaPalette( PalRgb far * pal );
long pascal far qglVgaScreen( void );
void pascal far qglVgaShutdown( void );
short pascal far qglZipCheck( short fh );
short pascal far qglZipFind( short fh, long member, long sizep );
long pascal far qglZScale( float f );

/* BASIC's own -- a string or array descriptor in the signature.
 * qgl keeps these behind *Bas wrappers; C calls the layer
 * under them instead.
 *
 *   qglArLoadBas
 *   qglArMap
 *   qglFileOpenBas
 *   qglTxtLoadBas
 */

#endif
