/* Generated by genhdr.py -- do not edit by hand.
 * Parameters from mgl's asm `proc` directives (authoritative: the
 * assembler derives stack offsets from them). Return types and the
 * long-vs-far-pointer distinction from the matching .bi declare.
 */
#ifndef __MGLAPI_H__
#define __MGLAPI_H__

/* Opaque: mgl STRUCs used only through pointers here. */
typedef struct cbez3d_s cbez3d;
typedef struct mouseinf_s mouseinf;
typedef struct pnt3d_s pnt3d;
typedef struct rgb_s rgb;
typedef struct tmr_s tmr;
typedef struct uar_s uar;
typedef struct vec3f_s vec3f;

short pascal far emsAlloc( long bytes );
short pascal far emsCheck( void );
short pascal far emsMapEx( short hnd, short lpg, short slot );
void pascal far kbdInit( void far * kbd );
long pascal far memAlloc( long bytes );
long pascal far memAvail( void );
void pascal far memCopy( void far * dst, void far * src, long bytes );
void pascal far memFree( long farptr );
short pascal far mouseInit( long dc, mouseinf far * mouseInf );
void pascal far mousePos( short x, short y );
/* sndDebugStat: implemented in mgl's C sub-libraries, not asm -- prototype omitted, no proc directive to derive it from. */
/* sndInit: implemented in mgl's C sub-libraries, not asm -- prototype omitted, no proc directive to derive it from. */
/* sndMasterGetVU: implemented in mgl's C sub-libraries, not asm -- prototype omitted, no proc directive to derive it from. */
/* sndOpenOutput: implemented in mgl's C sub-libraries, not asm -- prototype omitted, no proc directive to derive it from. */
void pascal far tmrDel( tmr far * tmr );
void pascal far tmrInit( void );
long pascal far tmrMs2Freq( long milisecs );
void pascal far tmrNew( tmr far * tmr, short mode, long _rate );
void pascal far u3dMtrxByVec4( float far * vOut, short vOutSize, float far * mIn, float far * vIn, short vInSize, short cnt );
void pascal far u3dMtrxConc( float far * pOut, float far * pIna, float far * pInb );
void pascal far u3dMtrxLookAt( float far * pOut, float far * pEye, float far * pAt, float far * pUp );
void pascal far u3dMtrxPersp( float far * pOut, float fov, float asp, float zn, float zf );
void pascal far uarClose( uar far * u );
short pascal far uarOpen( uar far * u, void * fname, short mode );
long pascal far uarRead( uar far * u, long destine, long bytes );
long pascal far uarReadH( uar far * u, long destine, long bytes );
long pascal far uarSize( uar far * u );
void pascal far uglArrLoad( void * fname, short typ, short elsz, long cnt, short slot );
void pascal far uglArrMap( long h, void * adesc, long idx );
void pascal far uglBlitMskScl( long dst, short x, short y, float xscale, float yscale, long src, short px, short py, short wdt, short hgt );
short pascal far uglBuildSurf( long dstDc, long texDc, long parm );
void pascal far uglClear( long dc, long color );
void pascal far uglClearZ( long zdc, short value );
long pascal far uglColor8( short red, short green, short blue );
void pascal far uglDel( long far * dc );
void pascal far uglDelView( long dc );
void pascal far uglEnd( void );
void pascal far uglHLine( long dc, short x1, short y, short x2, long color );
short pascal far uglInit( void );
void pascal far uglLine( long dc, short x1, short y1, short x2, short y2, long color );
long pascal far uglMapEx( long dc, short y, short slot );
long pascal far uglNew( short typ, short fmt, short xRes, short yRes );
long pascal far uglNewBMPEx( short typ, short cfmt, void * fname, short opt );
short pascal far uglNewMult( long * dcArray, short dcs, short typ, short fmt, short xRes, short yRes );
long pascal far uglNewView( long src, long ofs, short xRes, short yRes );
long pascal far uglNewZ( long dc, short typ );
long pascal far uglPalLoad( void * fname, short format );
void pascal far uglPalSet( short idx, short entries, rgb far * pal );
long pascal far uglPGet( long dc, short x, short y );
void pascal far uglPolyTP( long dstDC, vec3f far * vtx, short vtxCnt, short masking, long srcDC );
void pascal far uglPut( long dst, short x, short y, long src );
void pascal far uglPutMsk( long dst, short x, short y, long src );
void pascal far uglPutScl( long dstDC, short x, short y, float xScale, float yScale, long srcDC );
void pascal far uglRect( long dc, short x1, short y1, short x2, short y2, long color );
void pascal far uglRectF( long dc, short x1, short y1, short x2, short y2, long color );
void pascal far uglRestore( void );
void pascal far uglRowRead( long dc, short x, short y, short pixels, short buffFmt, long buff );
long pascal far uglSetVideoDC( short fmt, short xRes, short yRes, short vidPages );
short pascal far uglSetView( long dc, long ofs );
void pascal far uglSetVisPage( short visPg );
void pascal far uglSetWrkPage( short wrkPg );
void pascal far uglSetZ( long zdc );
void pascal far uglShadeRect( long dc, short x0, short y0, short x1, short y1, long cmap, short row );
void pascal far uglTriF( long dstDC, vec3f far * vtx, long col );
void pascal far uglTriT( long dstDC, vec3f far * vtx, short masked, long srcDC );
void pascal far uglTriTP( long dstDC, vec3f far * vtx, short masked, long srcDC );
void pascal far ugluCubicBez3D( pnt3d far * storage, cbez3d far * cbz, short levels );
void pascal far uglVLine( long dc, short x, short y1, short y2, long color );
short pascal far uglZMode( short mode );
long pascal far uglZScale( float scale );

#endif
