"""genhdr.py -- emit C prototypes for mgl from the asm + .bi pair.

    python3 tools/genhdr.py $MGL src/cport/mglapi.syms > src/cport/mglapi.h

mglapi.syms is the list of mgl entry points qrender actually calls,
derived once by intersecting the identifiers used across src/*.{bas,c,bi}
with the names mgl declares in inc/*.bi. Regenerate that list with:

    grep -rhoE "\\b(ugl|uglu|u3d|kbd|tmr|mouse|font|pal|snd|mem|ems|arch|uar|dos)[A-Za-z0-9_]*" \\
         src/*.bas src/*.c src/*.bi | sort -u > used.txt
    grep -rhoiE "declare +(function|sub) +[A-Za-z_][A-Za-z0-9_]*" $MGL/inc/*.bi \\
         | awk '{print $3}' | sed 's/[%&!#$]$//' | sort -u > decl.txt
    comm -12 used.txt decl.txt > src/cport/mglapi.syms

Parameters come from the `proc` directive: the assembler computes stack
offsets from it and the body addresses those names, so it cannot drift
from the implementation. Return type and the long-vs-far-pointer
distinction come from the .bi, which apicheck.py verified agrees with
the asm on every one of 279 shared functions.

Emitted as `pascal far`, matching how qb-qrender's existing C modules
already declare every uGL entry point they call.
"""
import re, glob, sys

def strip_comment(l):
    return l.split(';')[0]

def parse_asm(root):
    out = {}
    for f in glob.glob(root + '/src/**/*.asm', recursive=True):
        lines = open(f, errors='ignore').read().split('\n')
        for i, l in enumerate(lines):
            m = re.match(r'^([A-Za-z_][\w$]*)\s+proc\s+(.*)$', strip_comment(l))
            if not m:
                continue
            name, blob = m.group(1), m.group(2)
            j = i
            while blob.rstrip().endswith('\\') and j + 1 < len(lines):
                j += 1
                blob = blob.rstrip()[:-1] + ' ' + strip_comment(lines[j]).strip()
            if 'private' in blob.lower():
                continue
            mf = re.search(r'[A-Za-z_]\w*\s*:', blob)
            head = blob[:mf.start()] if mf else blob
            if 'public' not in head.lower():
                continue
            params = blob[mf.start():] if mf else ''
            pl = []
            for p in params.split(','):
                p = p.strip()
                if p and ':' in p:
                    n, t = p.split(':', 1)
                    pl.append((n.strip(), t.strip()))
            out[name.lower()] = (name, pl)
    return out

RET = {'%': 'short', '&': 'long', '!': 'float', '#': 'double', '': 'void'}

def parse_bi(root):
    out = {}
    for f in glob.glob(root + '/inc/*.bi'):
        txt = re.sub(r'_\s*\r?\n', ' ', open(f, errors='ignore').read())
        for line in txt.split('\n'):
            m = re.match(r'\s*declare\s+(function|sub)\s+([A-Za-z_]\w*)\s*([%&!#$]?)\s*\((.*)\)',
                         line, re.I)
            if not m:
                continue
            kind, name, sig, params = m.groups()
            ret = 'void' if kind.lower() == 'sub' else RET.get(sig, 'short')
            pl = []
            for p in params.split(','):
                p = p.strip()
                if not p:
                    continue
                mm = re.match(r'(.*?)\bas\s+([A-Za-z_]\w*)', p, re.I)
                pl.append((p.lower(), mm.group(2).lower() if mm else ''))
            out[name.lower()] = (name, ret, pl)
    return out

BAS_C = {'integer': 'short', 'long': 'long', 'single': 'float',
         'double': 'double', 'any': 'void'}

# asm primitive type names -> C. Anything not here is a STRUC and is
# emitted as an opaque typedef so the header compiles standalone.
PRIM = {'real4': 'float', 'real8': 'double', 'dword': 'long',
        'sdword': 'long', 'word': 'short', 'sword': 'short',
        'byte': 'unsigned char', 'sbyte': 'char', 'qword': 'double'}
OPAQUE = set()

def ctype(asm_t, bas_decl, bas_t):
    """asm gives the size; .bi says whether a dword is a value or a pointer."""
    a = asm_t.lower()
    if a.startswith('far ptr'):
        t = a[7:].strip()
        if not t or t.isdigit():
            return 'void far *'
        if t in PRIM:
            return PRIM[t] + ' far *'
        OPAQUE.add(t)
        return t + ' far *'
    if bas_decl.startswith('seg '):
        return BAS_C.get(bas_t, 'void') + ' far *'
    if not bas_decl.startswith('byval'):
        return BAS_C.get(bas_t, 'void') + ' *'
    return BAS_C.get(bas_t, {'word': 'short', 'dword': 'long'}.get(a, 'long'))

root, want = sys.argv[1], set(open(sys.argv[2]).read().split())
asm, bi = parse_asm(root), parse_bi(root)

print("/* Generated by genhdr.py -- do not edit by hand.")
print(" * Parameters from mgl's asm `proc` directives (authoritative: the")
print(" * assembler derives stack offsets from them). Return types and the")
print(" * long-vs-far-pointer distinction from the matching .bi declare.")
print(" */")
lines_out = []
ok = skip = 0
for name in sorted(want, key=str.lower):
    k = name.lower()
    if k not in bi:
        continue
    bn, ret, bpl = bi[k]
    if k not in asm:                      # C sub-library (snd*), no asm proc
        skip += 1
        lines_out.append(f"/* {bn}: implemented in mgl's C sub-libraries, not asm -- "
              f"prototype omitted, no proc directive to derive it from. */")
        continue
    an, apl = asm[k]
    if len(apl) != len(bpl):
        skip += 1
        lines_out.append(f"/* {bn}: asm/bi parameter count disagree ({len(apl)}/{len(bpl)}) -- omitted. */")
        continue
    args = ", ".join(f"{ctype(at, bd, bt)} {an_}" for (an_, at), (bd, bt) in zip(apl, bpl)) or "void"
    lines_out.append(f"{ret} pascal far {bn}( {args} );")
    ok += 1
print("#ifndef __MGLAPI_H__\n#define __MGLAPI_H__\n")
if OPAQUE:
    print("/* Opaque: mgl STRUCs used only through pointers here. */")
    for t in sorted(OPAQUE):
        print(f"typedef struct {t}_s {t};")
    print()
for l in lines_out:
    print(l)
print("\n#endif")
sys.stderr.write(f"emitted {ok} prototypes, skipped {skip}\n")
