#!/usr/bin/env python3
"""mkqglbi.py -- generate src/qgl/qgl.bi from src/qgl/qgl.inc.

    tools/mkqglbi.py src/qgl/qgl.inc src/qgl/qgl.bi
    tools/mkqglbi.py src/qgl/qgl.inc src/qgl/qgl.bi --check

qgl.bi used to be written by hand beside qgl.inc, with a comment telling
whoever changed one to change the other. That is a fact kept in two
places, and it drifted the moment SurfaceOps grew: the assembly said EMS
was 10 and BASIC said 2, so a BASIC caller asking for an EMS surface
indexed into the middle of the conventional-memory entry and called
whatever it found.

So qgl.bi is generated now, and --check fails the build when the copy on
disk no longer matches. The constants themselves are plain semantic
values -- 0, 1, 2 -- never a record size, because a constant that is
also an offset changes meaning whenever the record grows and says
nothing when it does.
"""

import re
import sys

# Every constant BASIC is allowed to name, and what it is for. Anything
# not listed here stays inside the layer.
EXPORT = [
    ("Which free figure qglMemAvail should report.", [
        "QGL_MEM_LARGEST", "QGL_MEM_TOTAL"]),
    ("Where a surface's pixels live.", [
        "QGL_SURF_CMEM", "QGL_SURF_EMS"]),
    ("Physical EMS page a surface is mapped through.", [
        "QGL_TEX_SLOT", "QGL_Z_SLOT"]),
    ("Depth mode, for qglSfZMode.", [
        "QGL_Z_OFF", "QGL_Z_SET", "QGL_Z_TEST"]),
    ("Drawing mode, for qglRsPoly.", [
        "QGL_M_WIRE", "QGL_M_FLAT", "QGL_M_TEX", "QGL_M_PTEX"]),
    ("Where a paged array store's records live.", [
        "QGL_AR_MEM", "QGL_AR_EMS"]),
]

# qgl.inc spells two of them without the QGL_ prefix
ALIAS = {"QGL_SURF_CMEM": "SURF_CMEM", "QGL_SURF_EMS": "SURF_EMS",
         "QGL_MEM_LARGEST": "MEM_LARGEST", "QGL_MEM_TOTAL": "MEM_TOTAL"}


SZ = {"db": 1, "dw": 2, "dd": 4, "dq": 8, "real4": 4, "real8": 8}


# Every STRUC's size, so `SIZEOF X` in a constant can be resolved -- and
# so a constant defined from one can be refused.
def sizeofs(inc: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for m in re.finditer(r"^(\w+)\s+struc\s*$(.*?)^\1\s+ends", inc, re.M | re.S):
        n = 0
        for line in m.group(2).splitlines():
            f = line.split()
            if len(f) >= 2 and f[1] in SZ:
                n += SZ[f[1]]
        out[m.group(1)] = n
    return out


# Values, and the names whose definition mentions a record size. An
# exported enum must never be one of those: SURF_EMS was
# `1 * (SIZEOF SurfaceOps)`, which meant 2 until the record grew and 10
# afterwards, in a value BASIC had already been told was 2.
def constants(inc: str) -> tuple[dict[str, int], set[str]]:
    out: dict[str, int] = {}
    derived: set[str] = set()
    sz = sizeofs(inc)
    for m in re.finditer(r"^(\w+)\s+equ\s+([^;\r\n]+)", inc, re.M):
        name, expr = m.group(1), m.group(2).strip()
        # `T X` is qgl.inc's own shorthand for `type X`, and it means the
        # same thing SIZEOF does here. Matching only SIZEOF let SF_MEM /
        # SF_EMS -- written `0 * T SurfaceOps` -- past the guard below.
        if re.search(r"\bSIZEOF\b|\bT\s+\w", expr):
            derived.add(name)
        for s, v in sz.items():
            expr = re.sub(r"\b(?:SIZEOF|T)\s+" + s + r"\b", str(v), expr)
        expr = re.sub(r"\b(" + "|".join(out) + r")\b", lambda k: str(out[k.group(1)]), expr) if out else expr
        if not re.fullmatch(r"[0-9A-Fa-fh\s+*()-]+", expr):
            continue
        try:
            out[name] = eval(re.sub(r"\b([0-9A-Fa-f]+)h\b", r"0x\1", expr), {}, {})
        except Exception:
            pass
    return out, derived


def render(vals: dict[str, int], derived: set[str]) -> str:
    L = ["''",
         "'' qgl.bi -- the qgl layer's constants, for BASIC callers.",
         "''",
         "'' GENERATED by tools/mkqglbi.py from qgl.inc. Do not edit: the",
         "'' build regenerates it and fails if this copy has drifted.",
         "''",
         "'' It exists because the same fact was kept in two places and did",
         "'' drift -- SurfaceOps grew, the assembly's EMS became 10 and this",
         "'' file still said 2, so a BASIC caller asking for an EMS surface",
         "'' indexed the middle of the conventional-memory entry.",
         "''"]
    for note, names in EXPORT:
        L.append("")
        L.append("'' " + note)
        w = max(len(n) for n in names)
        for n in names:
            src = ALIAS.get(n, n)
            if src not in vals:
                raise SystemExit(f"mkqglbi: {src} not found in qgl.inc")
            if src in derived:
                raise SystemExit(
                    f"mkqglbi: {src} is defined from SIZEOF. An exported\n"
                    f"  constant must be written out: it crosses into BASIC, and a\n"
                    f"  record size changes underneath it without saying so.")
            L.append(f"const {n:<{w}} = {vals[src]}")
    return "\r\n".join(L) + "\r\n"


def main(argv: list[str]) -> int:
    inc, bi = argv[1], argv[2]
    check = "--check" in argv
    vals, derived = constants(open(inc, encoding="latin-1").read())
    want = render(vals, derived)
    try:
        have = open(bi, "rb").read().decode("latin-1")
    except FileNotFoundError:
        have = ""
    if have == want:
        return 0
    if check:
        sys.stderr.write(f"mkqglbi: {bi} is stale -- run tools/mkqglbi.py\n")
        for a, b in zip(have.splitlines(), want.splitlines()):
            if a != b:
                sys.stderr.write(f"  on disk: {a}\n  qgl.inc: {b}\n")
                break
        return 1
    open(bi, "wb").write(want.encode("latin-1"))
    sys.stderr.write(f"{bi}: {sum(len(n) for _, n in EXPORT)} constants\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
