[sdl]
machine=svga_s3
output=surface
showdetails=false
showbasic=false

[dosbox]
memsize=64
startquiet=true
startbanner=false

[cpu]
core=normal
cputype=pentium_iii
cycles=max

[dos]
xms=true
ems=true
dpmi=false
log console=false

[mixer]
nosound=true

[autoexec]
@echo off
mount c /Users/alim/work/personal/qb-qrender/build/ctrl
mount q /Users/alim/work/other/d32x/toolchains/qb45
mount m /Users/alim/work/badlogic/mgl
set INCLUDE=M:\INC
c:
build.bat
exit
